name: hGear
favicon: null
layout_spectrum: 0.7823
typography_spectrum: 0.42483
title: hGear Home Automation Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8aaa9'
    - '#000000'
    - '#fdfa4f'
    - '#848685'
    - '#575757'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
